// Generated by gencpp from file robot_msg/robot.msg
// DO NOT EDIT!


#ifndef ROBOT_MSG_MESSAGE_ROBOT_H
#define ROBOT_MSG_MESSAGE_ROBOT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_msg
{
template <class ContainerAllocator>
struct robot_
{
  typedef robot_<ContainerAllocator> Type;

  robot_()
    : header()
    , mode(0)
    , state(0)
    , type()
    , comparams()  {
    }
  robot_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , mode(0)
    , state(0)
    , type(_alloc)
    , comparams(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _mode_type;
  _mode_type mode;

   typedef int8_t _state_type;
  _state_type state;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _type_type;
  _type_type type;

   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _comparams_type;
  _comparams_type comparams;





  typedef boost::shared_ptr< ::robot_msg::robot_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_msg::robot_<ContainerAllocator> const> ConstPtr;

}; // struct robot_

typedef ::robot_msg::robot_<std::allocator<void> > robot;

typedef boost::shared_ptr< ::robot_msg::robot > robotPtr;
typedef boost::shared_ptr< ::robot_msg::robot const> robotConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_msg::robot_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_msg::robot_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_msg::robot_<ContainerAllocator1> & lhs, const ::robot_msg::robot_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.mode == rhs.mode &&
    lhs.state == rhs.state &&
    lhs.type == rhs.type &&
    lhs.comparams == rhs.comparams;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_msg::robot_<ContainerAllocator1> & lhs, const ::robot_msg::robot_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_msg::robot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_msg::robot_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::robot_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_msg::robot_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::robot_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_msg::robot_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_msg::robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "82d518a77471a756a145acd21bc78f34";
  }

  static const char* value(const ::robot_msg::robot_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x82d518a77471a756ULL;
  static const uint64_t static_value2 = 0xa145acd21bc78f34ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_msg::robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_msg/robot";
  }

  static const char* value(const ::robot_msg::robot_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_msg::robot_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int8 mode    # slam建图 or nav导航\n"
"    # slam\n"
"int8 state   # 1 启动建图 2 保存地图\n"
"\n"
"string type  # 执行的命令类型\n"
"string[] comparams	# 执行命令\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::robot_msg::robot_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_msg::robot_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.mode);
      stream.next(m.state);
      stream.next(m.type);
      stream.next(m.comparams);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_msg::robot_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_msg::robot_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.mode);
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.type);
    s << indent << "comparams[]" << std::endl;
    for (size_t i = 0; i < v.comparams.size(); ++i)
    {
      s << indent << "  comparams[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.comparams[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_MSG_MESSAGE_ROBOT_H
