// Generated by gencpp from file action_pure/purePursuitFeedback.msg
// DO NOT EDIT!


#ifndef ACTION_PURE_MESSAGE_PUREPURSUITFEEDBACK_H
#define ACTION_PURE_MESSAGE_PUREPURSUITFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace action_pure
{
template <class ContainerAllocator>
struct purePursuitFeedback_
{
  typedef purePursuitFeedback_<ContainerAllocator> Type;

  purePursuitFeedback_()
    : state()  {
    }
  purePursuitFeedback_(const ContainerAllocator& _alloc)
    : state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::action_pure::purePursuitFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::action_pure::purePursuitFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct purePursuitFeedback_

typedef ::action_pure::purePursuitFeedback_<std::allocator<void> > purePursuitFeedback;

typedef boost::shared_ptr< ::action_pure::purePursuitFeedback > purePursuitFeedbackPtr;
typedef boost::shared_ptr< ::action_pure::purePursuitFeedback const> purePursuitFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::action_pure::purePursuitFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::action_pure::purePursuitFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::action_pure::purePursuitFeedback_<ContainerAllocator1> & lhs, const ::action_pure::purePursuitFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::action_pure::purePursuitFeedback_<ContainerAllocator1> & lhs, const ::action_pure::purePursuitFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace action_pure

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::action_pure::purePursuitFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::action_pure::purePursuitFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_pure::purePursuitFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::action_pure::purePursuitFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_pure::purePursuitFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::action_pure::purePursuitFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::action_pure::purePursuitFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "db0e51a034f26a3241c51e8fdd5c6481";
  }

  static const char* value(const ::action_pure::purePursuitFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdb0e51a034f26a32ULL;
  static const uint64_t static_value2 = 0x41c51e8fdd5c6481ULL;
};

template<class ContainerAllocator>
struct DataType< ::action_pure::purePursuitFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "action_pure/purePursuitFeedback";
  }

  static const char* value(const ::action_pure::purePursuitFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::action_pure::purePursuitFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"\n"
"# feedback 机器人实时姿态\n"
"geometry_msgs/Pose2D state\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::action_pure::purePursuitFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::action_pure::purePursuitFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct purePursuitFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::action_pure::purePursuitFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::action_pure::purePursuitFeedback_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ACTION_PURE_MESSAGE_PUREPURSUITFEEDBACK_H
