// Generated by gencpp from file mission_parse/reconnoitrewithtask.msg
// DO NOT EDIT!


#ifndef MISSION_PARSE_MESSAGE_RECONNOITREWITHTASK_H
#define MISSION_PARSE_MESSAGE_RECONNOITREWITHTASK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace mission_parse
{
template <class ContainerAllocator>
struct reconnoitrewithtask_
{
  typedef reconnoitrewithtask_<ContainerAllocator> Type;

  reconnoitrewithtask_()
    : header()
    , robot_num(0)
    , robot_id()  {
    }
  reconnoitrewithtask_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , robot_num(0)
    , robot_id(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _robot_num_type;
  _robot_num_type robot_num;

   typedef std::vector<int16_t, typename ContainerAllocator::template rebind<int16_t>::other >  _robot_id_type;
  _robot_id_type robot_id;





  typedef boost::shared_ptr< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> const> ConstPtr;

}; // struct reconnoitrewithtask_

typedef ::mission_parse::reconnoitrewithtask_<std::allocator<void> > reconnoitrewithtask;

typedef boost::shared_ptr< ::mission_parse::reconnoitrewithtask > reconnoitrewithtaskPtr;
typedef boost::shared_ptr< ::mission_parse::reconnoitrewithtask const> reconnoitrewithtaskConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mission_parse::reconnoitrewithtask_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mission_parse::reconnoitrewithtask_<ContainerAllocator1> & lhs, const ::mission_parse::reconnoitrewithtask_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.robot_num == rhs.robot_num &&
    lhs.robot_id == rhs.robot_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mission_parse::reconnoitrewithtask_<ContainerAllocator1> & lhs, const ::mission_parse::reconnoitrewithtask_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mission_parse

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "55fa6af62d5cdbbcabf1639481ef3b7d";
  }

  static const char* value(const ::mission_parse::reconnoitrewithtask_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x55fa6af62d5cdbbcULL;
  static const uint64_t static_value2 = 0xabf1639481ef3b7dULL;
};

template<class ContainerAllocator>
struct DataType< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mission_parse/reconnoitrewithtask";
  }

  static const char* value(const ::mission_parse::reconnoitrewithtask_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int16 robot_num\n"
"int16[] robot_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::mission_parse::reconnoitrewithtask_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.robot_num);
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct reconnoitrewithtask_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mission_parse::reconnoitrewithtask_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mission_parse::reconnoitrewithtask_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "robot_num: ";
    Printer<int16_t>::stream(s, indent + "  ", v.robot_num);
    s << indent << "robot_id[]" << std::endl;
    for (size_t i = 0; i < v.robot_id.size(); ++i)
    {
      s << indent << "  robot_id[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.robot_id[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MISSION_PARSE_MESSAGE_RECONNOITREWITHTASK_H
